### ISSUE TITLE
Backport patches from others llvm-spirv repo

### ISSUE THREAD

**Issue by Hopetech** [pierremoreau/llvm-spirv#8]
They are many repo around that try to implement the translator.
We should pick some patches from them.

**Comment by pierremoreau** [comment]
We need to clean up the code as well, like run clang-format and fix the line endings (most of the SPIR-V stuff has Windows-style line endings).

**Comment by pierremoreau** [comment]
@Hopetech I added the `override` keyword to functions that need it. I think I got most of them, but might still be missing some. At least it should cut on the number of warnings being emitted. :-) Patches are available on https://github.com/pierremoreau/llvm-spirv/tree/rebase_wip which is based on your master branch.

**Comment by pierremoreau** [comment]
And it now compiles against LLVM 5.0, and seems to run just as fine as before. I think we should: 1) run clang-format on the whole thing, and 2) fix the newline endings. Once that is done, let’s make this the new master, merge in the extra patches from https://github.com/pierremoreau/llvm-spirv/tree/rebase_integrate_with_mesa and start working on additional fixes + getting it to compile against LLVM HEAD.

**Comment by pierremoreau** [comment]
I think the new repo should have most, if not all patches. I’ll work on sending the ones local to this repository.
